apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
        - name: api
          resources:
            requests:
              cpu: "500m"
          command: [
                "/app/main"
          ]
          image: ec2-34-232-192-228.compute-1.amazonaws.com:5000/api
          imagePullPolicy: Always
          env:
            - name: HTTP_PORT
              value: :9000
          ports:
          - containerPort: 9000
            name: api-port
