apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment-stateless
spec:
  selector:
    matchLabels:
      app: nginx-stateless
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: nginx-stateless
    spec:
      containers:
      - name: nginx-stateless
        image: nginx:1.7.9
        ports:
        - containerPort: 80
